apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: moulalifinal-deploy
  name: moulalifinal-deploy
  namespace: moulali-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: moulalifinal-deploy
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: moulalifinal-deploy
    spec:
      containers:
      - image: moulali1122/moulalihcl:appfinal
        name: moulalihcl
        ports:
        - containerPort: 80
        resources: {}
status: {}

---  



apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: moulalifinal-deploy
  name: moulalilb1555
  namespace: moulali-project
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: moulalifinal-deploy
  type: NodePort
status:
  loadBalancer: {}
